---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: tenant-01
spec:
  healthChecks:
  - kind: Deployment
    name: podinfo
    namespace: apps
  interval: 5m0s
  path: ./kustomize
  prune: true
  serviceAccountName: tenant-01
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: tenant-01
  timeout: 2m0s

