---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./config/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: kyverno

