---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: apps
spec:
  healthChecks:
  - kind: Deployment
    name: podinfo
    namespace: apps
  interval: 5m0s
  path: ./kustomize
  prune: true
  serviceAccountName: sbabai
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: apps
  timeout: 2m0s
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: podinfo
      spec:
        template:
          spec:
            securityContext:
              runAsUser: 1000
              runAsGroup: 3000
              fsGroup: 2000
      

