---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 5m0s
  ref:
    branch: master
  secretRef:
    name: apps
  url: ssh://git@github.com/sasanbabai/podinfo

