---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure
  interval: 5m0s
  path: ./tenants
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

