---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tenant-01
  name: tenant-01

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tenant-01
  name: tenant-01
  namespace: tenant-01

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: tenant-01
  name: tenant-01-reconciler
  namespace: tenant-01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:tenant-01:reconciler
- kind: ServiceAccount
  name: tenant-01
  namespace: tenant-01

